version: "3"
services:
  web:
    image: nginx:1.15.7-alpine
    container_name: nginx
    ports:
      - 8080:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:cached
      - ./html:/var/www/html
    links:
      - php

  php:
    container_name: php
    build: ./php
    volumes:
      - ./html:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini:cached
      - ./php/log:/var/log:cached
    links:
      - postgres

  postgres:
    container_name: postgres
    build: ./postgresql
    volumes:
      - ./postgresql/databases:/var/lib/postgresql/data:z
    ports:
      - 15432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sample
      LANG: ja_JP.UTF-8
